name: Webhook workflow

on:
  webhooks:
    types:
      - push

jobs:
  webhook-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print webhook payload
        run: |
          echo "Received webhook payload"