version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: python --version
      - run: pip install tensorflow
      - run: pip install tensorflow_hub
      - run: python src/vgg.py
      # 其他构建步骤
